const applications = [
  {
    id: 1,
    company: 'Google',
    position: 'Software Engineer',
    status: 'Applied',
    appDate: '01/01/2020',
    interviewDate: '01/01/2020',
    notes: 'adlfkjadlfjasdlf;jasl;fjlf;kjasl;kfajsldkf',
    contactEmail: 'google.admin.com',
    contactPhone: '555-555-5555',
    contactName: 'Google Admin',
    followDate: '01/01/2020',
  },
  {
    id: 2,
    company: 'Facebook',
    position: 'Software Engineer',
    status: 'Applied',
    appDate: '01/01/2020',
    interviewDate: '01/01/2020',
    notes: 'adlfkjadlfjasdlf;jasl;fjlf;kjasl;kfajsldkf',
    contactEmail: 'facebook.admin.com',
    contactPhone: '555-555-5555',
    contactName: 'Facebook Admin',
    followDate: '01/01/2020',
  },
  {
    id: 3,
    company: 'Amazon',
    position: 'Software Engineer',
    status: 'Applied',
    appDate: '01/01/2020',
    interviewDate: '01/01/2020',
    notes: 'adlfkjadlfjasdlf;jasl;fjlf;kjasl;kfajsldkf',
    contactEmail: 'amazon.admin.com',
    contactPhone: '555-555-5555',
    contactName: 'Amazon Admin',
    followDate: '01/01/2020',
  },
  {
    id: 4,
    company: 'Microsoft',
    position: 'Software Engineer',
    status: 'Applied',
    appDate: '01/01/2020',
    interviewDate: '01/01/2020',
    notes: 'adlfkjadlfjasdlf;jasl;fjlf;kjasl;kfajsldkf',
    contactEmail: 'microsoft.admin.com',
    contactPhone: '555-555-5555',
    contactName: 'Microsoft Admin',
    followDate: '01/01/2020',
  },
  {
    id: 5,
    company: 'Twitter',
    position: 'Software Engineer',
    status: 'Applied',
    appDate: '01/01/2020',
    interviewDate: '01/01/2020',
    notes: 'adlfkjadlfjasdlf;jasl;fjlf;kjasl;kfajsldkf',
    contactEmail: 'twitter.admin.com',
    contactPhone: '555-555-5555',
    contactName: 'Twitter Admin',
    followDate: '01/01/2020',
  },
  {
    id: 6,
    company: 'Instagram',
    position: 'Software Engineer',
    status: 'Applied',
    appDate: '01/01/2020',
    interviewDate: '01/01/2020',
    notes: 'adlfkjadlfjasdlf;jasl;fjlf;kjasl;kfajsldkf',
    contactEmail: 'instagram.admin.com',
    contactPhone: '555-555-5555',
    contactName: 'Instagram Admin',
    followDate: '01/01/2020',
  },
]
