const applications = [
  {
    id: 1,
    company: 'Facebook',
    role: 'Software Engineer',
    status: 'Applied',
    appDate: '10/10/2018',
    interviewDate: '10/10/2018',
    notes: 'a;ljfa;ldfjal;sdfjlsdfjalskfjafsaafdasdf',
    contactEmail: 'google.admin.com',
    contactPhone: '555-555-5555',
    contactName: 'John Doe',
    followDate: '10/10/2018',
  },
  {
    id: 2,
    company: 'Google',
    role: 'Software Engineer',
    status: 'Applied',
    appDate: '10/10/2018',
    interviewDate: '10/10/2018',
    notes: 'a;ljfa;ldfjal;sdfjlsdfjalskfjafsaafdasdf',
    contactEmail: 'google.admin.com',
    contactPhone: '555-555-5555',
    contactName: 'John Doe',
    followDate: '10/10/2018',
  },
  {
    id: 3,
    company: 'Microsoft',
    role: 'Software Engineer',
    status: 'Applied',
    appDate: '10/10/2018',
    interviewDate: '10/10/2018',
    notes: 'a;ljfa;ldfjal;sdfjlsdfjalskfjafsaafdasdf',
    contactEmail: 'google.admin.com',
    contactPhone: '555-555-5555',
    contactName: 'John Doe',
    followDate: '10/10/2018',
  },
  {
    id: 4,
    company: 'Instagram',
    role: 'Software Engineer',
    status: 'Applied',
    appDate: '10/10/2018',
    interviewDate: '10/10/2018',
    notes: 'a;ljfa;ldfjal;sdfjlsdfjalskfjafsaafdasdf',
    contactEmail: 'google.admin.com',
    contactPhone: '555-555-5555',
    contactName: 'John Doe',
    followDate: '10/10/2018',
  },
  {
    id: 5,
    company: 'Apple',
    role: 'Software Engineer',
    status: 'Applied',
    appDate: '10/10/2018',
    interviewDate: '10/10/2018',
    notes: 'a;ljfa;ldfjal;sdfjlsdfjalskfjafsaafdasdf',
    contactEmail: 'google.admin.com',
    contactPhone: '555-555-5555',
    contactName: 'John Doe',
    followDate: '10/10/2018',
  },
  {
    id: 6,
    company: 'Amazon',
    role: 'Software Engineer',
    status: 'Applied',
    appDate: '10/10/2018',
    interviewDate: '10/10/2018',
    notes: 'a;ljfa;ldfjal;sdfjlsdfjalskfjafsaafdasdf',
    contactEmail: 'google.admin.com',
    contactPhone: '555-555-5555',
    contactName: 'John Doe',
    followDate: '10/10/2018',
  },
]

export default applications
